language: csharp
mono: none
os: linux
dist: bionic
dotnet: 2.2.105
script:
  - dotnet build src/EntityFrameworkCore.Encryption -c Release
  - /bin/bash -c 'cd ./test/EntityFrameworkCore.Encryption.Tests && ./run_tests.sh' 
